# Generated by Django 5.0 on 2023-12-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
