# Generated by Django 5.0 on 2023-12-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('we_name', models.CharField(max_length=255, verbose_name='Название salimo')),
                ('mini_descriptions', models.CharField(max_length=255, verbose_name='Мини Описание для salimo')),
                ('image', models.ImageField(upload_to='Картина для salimo')),
                ('we_creative', models.CharField(max_length=255, verbose_name='Название для we creative')),
                ('mini_descriptions1', models.CharField(max_length=255, verbose_name='Мини описание для we creative')),
                ('image1', models.ImageField(upload_to='Картина для we creative')),
                ('we_best', models.CharField(max_length=255, verbose_name='Название для we best')),
                ('mini_descriptions2', models.CharField(max_length=255, verbose_name='Мини описание для we best')),
                ('image2', models.ImageField(upload_to='Картина для we best')),
            ],
        ),
    ]
