# Generated by Django 4.2.5 on 2023-12-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_slide_about_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='we_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='mini_descriptions',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='mini_descriptions1',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='mini_descriptions2',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='we_best',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='we_creative',
        ),
        migrations.AddField(
            model_name='slide',
            name='descriptions',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
