# Generated by Django 4.2.5 on 2023-12-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_rename_we_name_slide_name_remove_slide_about_us_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип')),
                ('one_page', models.ImageField(upload_to='first_icon', verbose_name='Вступление')),
            ],
            options={
                'verbose_name': 'Настройки лаготипа',
                'verbose_name_plural': 'Настройка',
            },
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='main_photo', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
