# Generated by Django 4.2.5 on 2023-12-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_main_alter_slide_image_alter_slide_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='logo',
            field=models.ImageField(upload_to='Логотип'),
        ),
        migrations.AlterField(
            model_name='main',
            name='one_page',
            field=models.ImageField(upload_to='Фото'),
        ),
    ]
