# Generated by Django 5.0 on 2023-12-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_main_logo_alter_main_one_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'Настройки ', 'verbose_name_plural': 'Настройка лаготипа'},
        ),
    ]
