# Generated by Django 5.0 on 2023-12-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_main_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': ('Настройки ',), 'verbose_name_plural': 'Настройка лаготипа'},
        ),
        migrations.AlterField(
            model_name='main',
            name='logo',
            field=models.ImageField(upload_to='Logo', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='main',
            name='one_page',
            field=models.ImageField(upload_to='photo', verbose_name='Фото'),
        ),
    ]
