# Generated by Django 5.0 on 2023-12-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_alter_main_options_alter_main_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='one_page',
            field=models.ImageField(upload_to='photo', verbose_name='Логотип_2'),
        ),
    ]
