# Generated by Django 5.0 on 2023-12-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_main_one_page'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='Settings',
        ),
    ]
