# Generated by Django 5.0 on 2023-12-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_rename_main_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField(verbose_name='Обо мне')),
                ('my_goul', models.TextField(verbose_name='Моя цель')),
                ('my_advantages', models.TextField(verbose_name='Мои премущества')),
                ('my_guarantee', models.TextField(verbose_name='Моя гарантия')),
                ('my_image', models.ImageField(upload_to='My image')),
            ],
            options={
                'verbose_name': 'Инфорамация обо мне',
                'verbose_name_plural': 'Настройка информации',
            },
        ),
    ]
