# Generated by Django 5.0 on 2023-12-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_card', models.CharField(max_length=255, verbose_name='Название карточки')),
                ('dis_card', models.TextField(verbose_name='Описание карточки')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройка карты',
            },
        ),
    ]
