# Generated by Django 5.0 on 2023-12-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_mentor_mentor_fon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('friend_direction', models.CharField(max_length=255, verbose_name='Напровление')),
                ('friend_quote', models.TextField(verbose_name='Цитата')),
                ('friend_image', models.ImageField(upload_to='Фото')),
            ],
            options={
                'verbose_name': 'Настройки раздела друзья',
                'verbose_name_plural': 'Настройка раздела друзья',
            },
        ),
    ]
