# Generated by Django 5.0 on 2023-12-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name1', models.CharField(max_length=255, verbose_name='Имя')),
                ('friend_direction1', models.CharField(max_length=255, verbose_name='Напровление')),
                ('friend_quote1', models.TextField(verbose_name='Цитата')),
                ('friend_image1', models.ImageField(upload_to='Фото')),
            ],
            options={
                'verbose_name': 'Настройки раздела друзья',
                'verbose_name_plural': 'Настройка раздела друзья',
            },
        ),
    ]
