# Generated by Django 5.0 on 2023-12-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_friend2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend2',
            options={'verbose_name': 'Настройки раздела друзья1', 'verbose_name_plural': 'Настройка раздела друзья1'},
        ),
    ]
