# Generated by Django 5.0 on 2023-12-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_alter_friend2_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend2',
            new_name='Frie',
        ),
    ]
