# Generated by Django 5.0 on 2023-12-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_rename_friend_direction1_frie_direction1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Frie',
            new_name='Qwerty',
        ),
    ]
