# Generated by Django 5.0 on 2023-12-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_rename_frie_qwerty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Teacher Foto', verbose_name='Фото учителя')),
                ('name', models.CharField(max_length=155, verbose_name='Фото учителя')),
                ('month', models.CharField(max_length=155, verbose_name='Месяц который он обучал')),
            ],
            options={
                'verbose_name': 'Настройки раздела учетиля',
                'verbose_name_plural': 'Настройка учителей',
            },
        ),
        migrations.DeleteModel(
            name='Qwerty',
        ),
    ]
