# Generated by Django 5.0 on 2023-12-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_teacher_delete_qwerty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='month',
        ),
    ]
