# Generated by Django 5.0 on 2023-12-16 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_teacher_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='month',
            new_name='teach_month',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='teach_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='image',
            new_name='teahc_image',
        ),
    ]
