# Generated by Django 5.0 on 2023-12-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0026_rename_teahc_image_teacher_teach_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='mentor_fon',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='skype',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='youtube',
        ),
    ]
