# Generated by Django 5.0 on 2023-12-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_remove_mentor_facebook_remove_mentor_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Blog_image')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Новость ',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Timeofjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.CharField(max_length=255, verbose_name='Число проектов')),
                ('hours_work', models.CharField(max_length=255, verbose_name='Число время работ')),
                ('ofiices', models.CharField(max_length=255, verbose_name='Число офицов')),
                ('clients', models.CharField(max_length=255, verbose_name='Число клиентов')),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teach_month',
            field=models.CharField(max_length=255, verbose_name='Месяц который он обучал'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teach_name',
            field=models.CharField(max_length=255, verbose_name='Имя учителя'),
        ),
    ]
