# Generated by Django 5.0 on 2023-12-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_blogpost_timeofjob_alter_teacher_teach_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeofjob',
            options={'verbose_name': 'Мои проекты', 'verbose_name_plural': 'Мои проекты'},
        ),
    ]
