# Generated by Django 5.0 on 2023-12-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_alter_timeofjob_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timeofjob',
            new_name='Mypro',
        ),
    ]
