# Generated by Django 5.0 on 2023-12-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_rename_timeofjob_mypro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mypro',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_at',
            new_name='created',
        ),
    ]
