# Generated by Django 5.0 on 2023-12-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0032_mypro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mytpoject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Image My projects')),
                ('title', models.CharField(max_length=255, verbose_name='Навазние проекта')),
                ('descriptions', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Мои проекты',
                'verbose_name_plural': 'Мои проекты',
            },
        ),
    ]
