# Generated by Django 5.0 on 2023-12-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0034_contact_alter_mypro_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
