# Generated by Django 5.0 on 2023-12-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0035_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.CharField(default=1, max_length=255, verbose_name='Email адресс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='number',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='time',
            field=models.CharField(default=1, max_length=255, verbose_name='С сколько до скольки ты в гиксе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='week',
            field=models.CharField(default=1, max_length=255, verbose_name='Дни когда ты в гиксе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='week_of',
            field=models.CharField(default=1, max_length=255, verbose_name='дни когда ты не в гиксе'),
            preserve_default=False,
        ),
    ]
