# Generated by Django 5.0 on 2023-12-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0036_settings_email_settings_number_settings_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='insgram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
