# Generated by Django 5.0 on 2023-12-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0037_mentor_insgram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Инфорамация о менторе', 'verbose_name_plural': 'Настройка ментора'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='insgram',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
