# Generated by Django 5.0 on 2023-12-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0040_feedback_delete_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email адресс'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона'),
        ),
    ]
