# Generated by Django 5.0 on 2023-12-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0041_delete_feedback_alter_settings_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='fonbb',
            field=models.ImageField(default=1, upload_to='Mentor Фон'),
            preserve_default=False,
        ),
    ]
